# Generated by Django 4.2.27 on 2025-12-23 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0002_itineraryitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(help_text="Poll question", max_length=500),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when poll was created"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this poll",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="Trip this poll belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll",
                "verbose_name_plural": "Polls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(help_text="Option text", max_length=200)),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="Poll this option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll Option",
                "verbose_name_plural": "Poll Options",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when vote was cast"
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        help_text="Selected option",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.polloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="Poll being voted on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who voted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
                "indexes": [
                    models.Index(
                        fields=["poll", "user"], name="polls_vote_poll_id_cfe401_idx"
                    )
                ],
                "unique_together": {("poll", "user")},
            },
        ),
    ]
