# Generated by Django 4.2.27 on 2025-12-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_color",
            field=models.CharField(default="blue", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_icon",
            field=models.CharField(default="person", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_style",
            field=models.CharField(default="circle", max_length=20),
        ),
    ]
