# Generated by Django 4.2.27 on 2025-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image attachment",
                null=True,
                upload_to="chat_images/",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional video attachment",
                null=True,
                upload_to="chat_videos/",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True, help_text="Message content"),
        ),
    ]
