# Generated by Django 4.2.27 on 2025-12-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_image_chatmessage_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="video",
        ),
    ]
