# Generated by Django 4.2.27 on 2025-12-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the itinerary item", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the item",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order position in the itinerary (lower = earlier)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when item was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when item was last updated"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="Trip this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_items",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerary Item",
                "verbose_name_plural": "Itinerary Items",
                "ordering": ["order", "created_at"],
                "unique_together": {("trip", "order")},
            },
        ),
    ]
