# Generated by Django 4.2.27 on 2025-12-23 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0003_tripinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this item",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_itinerary_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
