# Generated by Django 4.2.27 on 2025-12-24 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0004_itineraryitem_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripNotificationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unread_chat_count", models.PositiveIntegerField(default=0)),
                ("unread_poll_count", models.PositiveIntegerField(default=0)),
                ("unread_itinerary_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="Trip context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_states",
                        to="trips.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User getting notifications",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_notification_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "trip"], name="trips_tripn_user_id_822cb7_idx"
                    )
                ],
                "unique_together": {("user", "trip")},
            },
        ),
    ]
