# Generated by Django 4.2.27 on 2025-12-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image for the trip",
                null=True,
                upload_to="trip_covers/",
            ),
        ),
    ]
