# Generated by Django 4.2.27 on 2025-12-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_trip_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="cover_image",
        ),
    ]
