# Generated by Django 4.2.27 on 2025-12-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_remove_trip_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itineraryitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when item was created",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when trip was created",
            ),
        ),
        migrations.AlterField(
            model_name="tripinvitation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
