# Generated by Django 4.2.27 on 2025-12-25 06:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_alter_itineraryitem_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invited_email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email of the invited user",
                        max_length=254,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for accepting the invite",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="Trip the user is invited to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Invite",
                "verbose_name_plural": "Trip Invites",
                "ordering": ["-created_at"],
                "unique_together": {("trip", "invited_email")},
            },
        ),
        migrations.DeleteModel(
            name="TripInvitation",
        ),
    ]
