# Generated by Django 4.2.27 on 2025-12-25 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0010_tripinvite_delete_tripinvitation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tripinvite",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tripinvite",
            name="invited_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Registered user who is invited",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tripinvite",
            name="invited_email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Email of the invited user",
                max_length=254,
                null=True,
            ),
        ),
    ]
