# Generated by Django 4.2.27 on 2025-12-25 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0011_alter_tripinvite_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripinvite",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who sent the invite",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_trip_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
